name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build and prepare for GitHub Pages
        env:
          # IMPORTANT: Create a repository secret named PAGE_ACCESS_PASSWORD in GitHub
          # Go to your repository -> Settings -> Secrets and variables -> Actions -> New repository secret
          # Name it PAGE_ACCESS_PASSWORD and set it to your desired password for protected pages
          NEXT_PUBLIC_PAGE_ACCESS_PASSWORD: ${{ secrets.PAGE_ACCESS_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run our custom script that handles everything
          ./scripts/prepare-github-pages.sh
        
      - name: Add CNAME if using custom domain
        run: |
          # Create a CNAME file if you're using a custom domain
          # echo "yourdomain.com" > out/CNAME
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
